#!/usr/bin/env bash

set -x

# Read branch to merge
BRANCH=$1

# Check if a branch was provided
if [ -z "$BRANCH" ]; then
    echo "Please provide a branch to merge"
    echo "merge <branch>"
    exit 1
fi

git merge "$BRANCH"
